"""First commit

Revision ID: af686bfa68c3
Revises: b268bfe3ec11
Create Date: 2024-03-17 20:44:04.891085

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af686bfa68c3'
down_revision: Union[str, None] = 'b268bfe3ec11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('title', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
                    sa.Column('description', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
                    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='notes_pkey')
                    )
    # ### end Alembic commands ###
